### ISSUE TITLE
Refactor / Dockerize all nodes for SONIA modules

### ISSUE THREAD

**Issue by kevincharbonneau** [sonia-auv/sonia_messages#5]
# Context
This task will be related to many other task. 

Most of SONIA's modules need to be modified so that they can integrate a dockerized solution. In all cases, it's either a refactor or a complete dockerization of the module.

# Changes
Here's the list of the modules to change : 

| **Number** | **Module name**        | **Arch. Type**  | **Done** | **Tested** | **Additional Notes** |
| ---- | ----------------- |:------------:|:-----:|:-----------:|:-----:|
| 1 | [provider_kill_mission](https://github.com/sonia-auv/provider_kill_mission)     |    Perception   |✅   | ✅  | [link to PR]() |
| 2 | [proc_mapping](https://github.com/sonia-auv/proc_mapping)   |    Perception   | - | -| [link to PR]() |
| 3 | [proc_navigation](https://github.com/sonia-auv/proc_navigation)      |   Perception   | -  | - | [link to PR]()  |
| 4 | [proc_actuators](https://github.com/sonia-auv/proc_actuators)      |    Perception   |-  | - | [link to PR]() |
| 5 | [proc_hydrophone](https://github.com/sonia-auv/proc_hydrophone)      |    Perception   | -  | - | [link to PR]() |
| 6 | [proc_sonar](https://github.com/sonia-auv/proc_sonar)      |    Perception   | - | - | [link to PR]()|
| 7 | [provider_dvl](https://github.com/sonia-auv/provider_dvl)      |    Perception   | -| - | [link to PR]() |
| 8 | [provider_hydrophone](https://github.com/sonia-auv/provider_hydrophone)      |    Robot   | - | - | [link to PR]() |
| 9 | [provider_thruster](https://github.com/sonia-auv/provider_thruster)    |    Perception  | -  | - | [link to ISSUE]() |
| 10 | [provider_imu](https://github.com/sonia-auv/provider_imu) |    Perception   | - | -|  |
| 11 | [provider_vision](https://github.com/sonia-auv/provider_vision)      |    Perception   | - | -|  Install Dalsa Driver |
| 12 | [provider_system](https://github.com/sonia-auv/provider_system)    |    Perception  | - | -|   [link to ISSUE]()
| 13 | [provider_power](https://github.com/sonia-auv/provider_power)      |    Perception   | -  | - | [link to PR]() |
| 14 | [provider_actuators](https://github.com/sonia-auv/provider_actuators)      |    Perception   | - | -| [link to PR]()|
| 15 | [provider_sonar](https://github.com/sonia-auv/provider_sonar)      |    Perception   |-| -|   [link to ISSUE]() |
| 16 | [interface_RS485](https://github.com/sonia-auv/interface_RS485)    |    Perception   | - | -  |[link to ISSUE]()|
| 17 | [proc_detection](https://github.com/sonia-auv/proc_detection)      |  L4T Perception  | -| .. |
| 18 | [proc_ura](https://github.com/sonia-auv/proc_ura)      |    Perception  | - | -|  Will potentially be archived |
| 19 | [lib_atlas](https://github.com/sonia-auv/lib_atlas)    |    Perception  | - | - | We need to find out if we install it in sonia-message or ...|
| 20 | [proc_image_processing](https://github.com/sonia-auv/proc_image_processing)      |    Perception   | - | -| [link to ISSUE]() |
| 21 | [proc_control](https://github.com/sonia-auv/proc_control)      |    Perception  | - | -| Wait for modifications to be completed |

# Comments
Possible status : 
Completed Or Tested :white_check_mark:
Potential Issue :warning:
Pending approval 🔍

**Comment by gauthiermartin** [comment]
@kevincharbonneau `provider_kill_mission` and `proc_navigation`  dockerfile does not seem to work ... @coumarc9 and I are currently investigating issue.

We noticed  that will need to add `.dockerignore` file also

**Comment by coumarc9** [comment]
I fix proc_mapping with these changes:
![image](https://user-images.githubusercontent.com/24485778/87230384-c912c400-c37d-11ea-8d3a-eff8df8f8df2.png)

And this docker-compose file:

```
version: "3"

services:
  ros-master:
    network_mode: host
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore
    restart: always

  proc_mapping:
    image: docker.pkg.github.com/sonia-auv/proc_mapping/proc_mapping:x86-perception-feature-cicd-migration-fix-fix
    network_mode: host
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
      - "ROS_IP=127.0.0.1"
    restart: always
```

We should probably fix `provider_kill_mission` and `proc_navigation` and the template before continuing the migration.
